services:
    web:
        build: './build/php/'
        ports:
            - "8007:443"
        volumes:
            - .:/var/www/livre-jeu
        links:
            - db:db
    db:
        build: './build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3027:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=thisisapassworddamned
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8077:80"
        links:
            - db:db
###> symfony/mailer ###
    mailer:
        image: axllent/mailpit
        ports:
            - "1025"
            - "8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1